#!/usr/bin/env sh

## UNFORTUNATELY THE SITE AT "https://playground.cazador.codes" IS DONN. I WILL FIX IT WHEN I HAVE TIME.

# Playground

## The functions in this file can be invoked like:
### ./README run

set -exu

## Setup Dependencies
init() {
    go mod download
    export assetsDir="cmd/webapp/assets/"
    mkdir -p "${assetsDir}"
    cp "$(go env GOROOT)/misc/wasm/wasm_exec.js" cmd/server/assets/
}

assets() {
    curl -L 'https://unpkg.com/htmx.org@1.9.10' > cmd/server/assets/htmx.js
}

## Build Webapp Assets
build_webapp() {
  export webappPackage="cmd/webapp"
  export serverPackage="cmd/server"
  rm -rf "${serverPackage}/webapp"
  cp -rf "${webappPackage}" "${serverPackage}"

  GOOS=js GOARCH=wasm go build -ldflags="-s -w" -o "${serverPackage}/webapp/assets/main.wasm" "./${webappPackage}/"
}

## Run
run() {
  build_webapp
  docker build -t playground:dev .
  docker run -p 8080:8080 playground:dev
}

deploy() {
  doctl apps create --spec .do/app.yaml
}

if [ $# -ne 0 ]; then
    "$1"
fi
