name: playground
region: sfo
domains:
  - domain: playground.cazador.codes
    type: PRIMARY
    zone: cazador.codes
  - domain: playground.crhntr.com
    type: ALIAS
    zone: crhntr.com
  - domain: play.cazador.codes
    type: PRIMARY
    zone: cazador.codes
  - domain: play.crhntr.com
    type: ALIAS
    zone: crhntr.com
ingress:
  rules:
    - component:
        name: web
      match:
        path:
          prefix: /
services:
  - name: web
    github:
      repo: crhntr/playground
      branch: main
      deploy_on_push: true
    dockerfile_path: Dockerfile
    http_port: 8080
    instance_count: 1
    instance_size_slug: basic-xxs
envs:
  - key: GITHUB_TOKEN
    scope: RUN_TIME
    type: SECRET
    value: EV[1:zuw5cSGOMY7yIRZaZt48ME+KpNliqgyS:TkItqTacGGeA2RB94uK45XEza/xRYNVpQyT/rxGK76stlUCmFxbrxShHrafCQIRj+uITSktk020fqbFG62jXFJRmeul/N23jRbRiwlgXjyZykT1b5O0X/e5M6kqx1dXpb9eyFRvqjVEszuPaCw==]